### ISSUE TITLE
Wineprefix in Opentrack

### ISSUE THREAD

**Issue by Sag05** [TheZoq2/dcs_on_linux#13]
I installed dcs openbeta through Lutris with no issues, and after some tinkering i got opentrack to work (problems beeing pacakages not installed) added the `Headtracker.dll` to `bin` and got the log file as described in the readme of the [download]( http://facetracknoir.sourceforge.net/information_links/download.htm). However i still dont get any head movement in dcs. i have ESYNC enabled on dcs and opentrack. Might be me not understanding how the wineprefix should be set up.

![WineSettings](https://user-images.githubusercontent.com/34776708/150884804-135080f9-fb76-44ce-a328-8a0d3a2f26e6.png)

Running Ubuntu 20.04.3 LT

**Comment by TheZoq2** [comment]
I can't help you much with that setup, I didn't manage to do it when I tried ages ago but din't really remember the details.

Looking at the screenshot, it seems like you set the wine to a wineprefix, I think you may want to set it to a wine executable, but I'm not sure.

What I do know is that you can use opentrack to emulate a controller which you can bind in DCS which worked really well for me until I upgraded to VR

**Comment by bekopharm** [comment]
Hej,
late for the party but after my own share of experiencing the WINEPREFIX pain with OpenTrack and Wineglue I propose another route as I described it [here](https://beko.famkos.net/2022/03/02/primary-buffer-panel-march-update/) for Elite Dangerous with Proton. I'm using the same approach for Star Citizens with Lutris.

Relevant snippets:

> So my _current_ strategy is to download and drop the Windows build of Opentrack into the game folder and chain-load the EXE with the game where the Opentrack EXE would listen on UDP while my native Opentrack BIN would send via UDP.

> Why running Opentrack twice? The native build performs a lot better with my webcam and every frame really count here. Reading data via UDP is not much of a burden for Proton. This also saves me the trouble of fiddling with Wine Glue [...]

My script snippet to do so is for Proton but with Wine (or Lutris) it's even easier and basically is something like this:

```bash
#!/bin/bash
export WINEPREFIX=/path/to/prefix
/usr/bin/wine /path/to/prefix/drive_c/opentrack.exe
```

You can look up the prefix and wine binary used by Lutris simply by checking the process list with e.g. `ps` - it's even possible that Lutris has a way to automatically run two EXE binaries for you but I'm not sure on that.
