### ISSUE TITLE
Black Screen Persistant After Simbolic Link

### ISSUE THREAD

**Issue by AdozenBABYdogs** [TheZoq2/dcs_on_linux#16]
The black screen is not going away after creating a symbolic link. 

I have DCS World OpenBeta installed in 
`/mnt/ExtDrv/DCS World OpenBeta/`

I create the Symbolic Link in this directory using this code
`ln -s bin/webrtc_plugin.dll`

After that, I run the game in the Bin directory with this command
`WINEDLLOVERRIDES="wbemprox=n;msdmo=n" wine DCS.exe`

The game boots up into the black screen.  Terminal outputs
```
0100:fixme:d3d11_device_context_VSSetShader Dynamic Linking is not implemented yet
0100:fixme:d3d11_device_context_PSSetShader Dynamic Linking is not implemented yet
```
repetitively until I close the game

**Comment by TheZoq2** [comment]
You need to run the game with proton, not wine (well, wine might work but I don't know anyone who has tested it). I'd recommend either lutris or steam
