### ISSUE TITLE
SRS with wine and .NET

### ISSUE THREAD

**Issue by reiuajgerhiouhatur** [TheZoq2/dcs_on_linux#25]
I finished building srsrs, but got `Address family not supported by protocol (os error 97)` whenever I forced my username with -u flag.

Hearing that running it all in wine was recommended, I got started:

After a lot of trial and error I could not succeed with starting SR-ClientRadio.exe in a seperate wineprefix. 
First I tried to run it in my default ~/.wine prefix, which resulted in this:
```
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.5 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
011c:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"SR-ClientRadio.exe" cannot be loaded
011c:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\username\\Downloads\\DCS-SimpleRadioStandalone-2.0.8.5\\SR-ClientRadio.exe" failed, status c0000135
```
After a bit of googling I guessed this has to do with a wrong .NET version, so here are my `winetricks list-installed` (default prefix):
```
remove_mono internal
remove_mono internal
winxp
dotnet40
dotnet452
win10
dotnet48
```
But as mentioned in the guide, I need win10 with dotnet452 in a (64-bit)? prefix. So I fiddled around in the winetricks menu and followed the .NET installers, which warned me about win10 being too new or that they require a 32-bit system, so it automatically switched back to a Windows version from 2003. When I selected win10 again, I only got a sort of "pop-up something went wrong" error but winetricks stayed quiet. Following I ran `WINEPREFIX='{pathtonewprefix}' wine ./SR-ClientRadio.exe` and met a `wine: Bad EXE format`. So I deleted the entire prefix again and don't know what to try next.
Does someone have an exact setup for all this mess I can replicate?

**Comment by Runlevel-zero** [comment]
What did you end up doing? I am just starting to dig into this.

**Comment by reiuajgerhiouhatur** [comment]
I forgot to put this here, sorry. 
After writing this issue and trying new approaches, I could no longer reproduce this exact error message.
My setup ended up being the following:

1. Purge wine entirely and create a clean prefix. (run these commands in your prefix obv.)
2. `winetricks dotnet48 win10`
3. `wine reg ADD 'HKCU\Software\Wine\DllOverrides' '/f' '/v' 'd3d9' '/t' 'REG_SZ' '/d' 'native'`
4. `wine SR-ClientRadio.exe`

The autoconnect feature worked flawlessly with Steam Edition.

from: https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/653

after that: (Just for fun: It's also possible, even if not recommended, to run the `Installer.exe` to install the DCS Scripts.)

**Comment by badbabykosh** [comment]
> I forgot to put this here, sorry. After writing this issue and trying new approaches, I could no longer reproduce this exact error message. My setup ended up being the following:
> 
> 1. Purge wine entirely and create a clean prefix. (run these commands in your prefix obv.)

What does this mean? "create a clean prefix"???

**Comment by xleax611** [comment]
> I forgot to put this here, sorry. After writing this issue and trying new approaches, I could no longer reproduce this exact error message. My setup ended up being the following:
> 
>     1. Purge wine entirely and create a clean prefix. (run these commands in your prefix obv.)
> 
>     2. `winetricks dotnet48 win10`
> 
>     3. `wine reg ADD 'HKCU\Software\Wine\DllOverrides' '/f' '/v' 'd3d9' '/t' 'REG_SZ' '/d' 'native'`
> 
>     4. `wine SR-ClientRadio.exe`
> 
> 
> The autoconnect feature worked flawlessly with Steam Edition.
> 
> from: [ciribob/DCS-SimpleRadioStandalone#653](https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/653)
> 
> after that: (Just for fun: It's also possible, even if not recommended, to run the `Installer.exe` to install the DCS Scripts.)

uh bit confused simple this please
