### ISSUE TITLE
DCS Steam Edition on Proton crashes when loading in on multiplayer

### ISSUE THREAD

**Issue by socallmemaeb** [TheZoq2/dcs_on_linux#7]
Following the advice in this page, I have set up DCS Steam edition open beta on Arch Linux. Singleplayer works perfectly fine, however, when trying to load into a server, the game freezes and crashes on the vehicle select screen. [log file](https://github.com/TheZoq2/dcs_on_linux/files/6029142/dcs.log)

**Comment by TheZoq2** [comment]
Huh, that's weird. I've had no problems like that, and the log file ends very abruptly. More so than usual

The last messages seem to be sound related, I wonder if this is some weird script running on the server you're trying to connect to. Have you tried multiple servers?

Another option would be to use standalone instead as that's what most people run these days

**Comment by socallmemaeb** [comment]
OK, I've tried some other servers, and a few let me get through the vehicle select screen, however they crash on briefing/when loading the game world. Here is [the log file](https://github.com/TheZoq2/dcs_on_linux/files/6034719/dcs.log) from trying to join the German Just Dogfight server, it crashed with the world loaded, however with the cockpit invisible.
I'm going to try the standalone version now.

**Comment by socallmemaeb** [comment]
I've got DCS Standalone to work through Lutris, and it generally gets further along, even letting me play for a bit on some servers. However, it still crashes. Here is [dcs.log](https://github.com/TheZoq2/dcs_on_linux/files/6035709/dcs.log) for a crash in vehicle select, here is [dcs.log](https://github.com/TheZoq2/dcs_on_linux/files/6035730/dcs.log) from a crash after a few minutes of flight in the Dogfight server

**Comment by TheZoq2** [comment]
That's super strange. Looks like it's crashing harder than usual as the ED crash reporter doesn't even have time to write anything.

I have 2 things you might check: Run lutris/steam from a terminal and see if you get more info printed there than in the game logs. You should also make sure you have very up-to-date graphics libraries. I've had the whole system crash several times while not using mesa-git for example.

**Comment by socallmemaeb** [comment]
I've tried a few things, and I've come to the conclusion that the issue is in my hardware, sadly. My laptop simply lacks the memory to run complex multiplayer missions. I was able to fly a mission on a small, local server, but as soon as i tried to get some external views my game crashed. This also coincided with my PC running out of RAM. Sorry for the confusion, and thanks for all the help!

**Comment by TheZoq2** [comment]
No problem, glad you found out the root cause. It's well known that DCS eats RAM. I run 32 gigs and have had it get OOM killed a few times (though I did have other stuff open then)

**Comment by socallmemaeb** [comment]
Yep, got a bunch more swap memory, and it runs pretty well now.
